import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
const inter = Inter({ subsets: ["latin"] });
import  {Toaster} from "react-hot-toast"
// import { getUser } from "../components/Navbar";
import AdminPage from "./admin/page";
import AddProduct, { api } from "./admin/add-product/page";
import { cookies } from "next/headers";
import { EnumLike } from "zod";
import AddCategory from "./admin/add-category/page";
import { error } from "console";
export const metadata: Metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
};
export type  UserType = {
  success: boolean,
  result: {
    porfilePic: {
      url: string,
      
    }
    userName: string,
    role: string,
    email: string,
  }
}
export async function getUser(): Promise<UserType>{
  'use server'
  const user = await fetch(`${api}/user`, {
    headers: { token: `${process.env.BEARER}${cookies().get("token")?.value}` },
  })
    .then((res) => res.json())
    .catch((error) => console.log("usermenu", error));
  // if(user.result.role === "admin") redirect("/admin")
  return await user
 }

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getUser()
  return (
    <html lang="en">
      <body className={inter.className}>
       
          <Navbar user={user}/>
           
          <main className="mx-auto min-w-[300px] max-w-6xl p-4">
           {/* <AdminPage user={user} /> */}
           {/* <AddProduct user={user} /> */}
           {/* <AddCategory user={user} /> */}
           {/* <AdminPage user={user} /> */}
            {children}
            <Toaster toastOptions={{error: {style: {background: '#ff005d', color: "white"}}}}/>
          </main>
          <Footer />
         
      </body>
    </html>
  );
}
